/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Cursos;
import controlador.Grado;
import controlador.Profesor;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Metodos_Admin;
import modelo.conexionBD;
import vista.registroAlumno.RegistroAlumno;
import vista.registroPadre.RegistroPadre;
import vista.registroProfesor.RegistroProfesor;


/**
 *
 * @author daniel
 */
public class DashboardAdmin extends javax.swing.JFrame {

    static boolean maximized = true;
    int xMouse;
    int yMouse;
   
 
    
           DefaultTableModel modelo = new DefaultTableModel();
         Metodos_Admin metodos = new Metodos_Admin();
    
    

    public DashboardAdmin() {
        initComponents();
        setLocationRelativeTo(null);
          Metodos_Admin metodos = new Metodos_Admin();
          CargarProfesor();
         
}
   
        
   

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lnlNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTimeline = new javax.swing.JLabel();
        lblNews = new javax.swing.JLabel();
        btnTrending = new javax.swing.JButton();
        lblTrending = new javax.swing.JLabel();
        lblQA = new javax.swing.JLabel();
        txtCierre = new javax.swing.JButton();
        btnQA1 = new javax.swing.JButton();
        btnPadrePanel = new javax.swing.JButton();
        btnAlumnoPanel = new javax.swing.JButton();
        btnProfesorPanel = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        profesor = new javax.swing.JPanel();
        btnActualizarP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProfesor = new javax.swing.JTable();
        btnEliminarP = new javax.swing.JButton();
        btnRegistrarP = new javax.swing.JButton();
        btnBuscarP = new javax.swing.JButton();
        alumno = new javax.swing.JPanel();
        btnBuscarA = new javax.swing.JButton();
        btnRegistrarA = new javax.swing.JButton();
        btnEliminarA = new javax.swing.JButton();
        btnModificarA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        padre = new javax.swing.JPanel();
        btnEliminarPadre = new javax.swing.JButton();
        btnBuscarPadre = new javax.swing.JButton();
        btnModificarPadre = new javax.swing.JButton();
        btnRegistrarPadre = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cube UI");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(102, 0, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/User.png"))); // NOI18N
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        lnlNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lnlNombre.setForeground(new java.awt.Color(44, 62, 80));
        pnlMenu.add(lnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 226, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 140, 141));
        jLabel3.setText("Perfil");
        pnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 52, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 152, 219));
        jLabel5.setText("Learn More");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 140, 141));
        jLabel4.setText("Padre");
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblTimeline.setBackground(new java.awt.Color(0, 204, 106));
        lblTimeline.setOpaque(true);
        pnlMenu.add(lblTimeline, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 772, 195, 8));

        lblNews.setBackground(new java.awt.Color(255, 255, 255));
        lblNews.setOpaque(true);
        pnlMenu.add(lblNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 772, 105, 8));

        btnTrending.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnTrending.setForeground(new java.awt.Color(44, 62, 80));
        btnTrending.setText("TRENDING");
        btnTrending.setContentAreaFilled(false);
        btnTrending.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTrending.setFocusable(false);
        btnTrending.setPreferredSize(new java.awt.Dimension(100, 27));
        btnTrending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrendingActionPerformed(evt);
            }
        });
        pnlMenu.add(btnTrending, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 739, 110, -1));

        lblTrending.setBackground(new java.awt.Color(255, 255, 255));
        lblTrending.setOpaque(true);
        lblTrending.setPreferredSize(new java.awt.Dimension(100, 0));
        pnlMenu.add(lblTrending, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 772, 110, 8));

        lblQA.setBackground(new java.awt.Color(255, 255, 255));
        lblQA.setOpaque(true);
        lblQA.setPreferredSize(new java.awt.Dimension(100, 0));
        pnlMenu.add(lblQA, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 772, 110, 8));

        txtCierre.setBackground(new java.awt.Color(255, 255, 255));
        txtCierre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        txtCierre.setForeground(new java.awt.Color(44, 62, 80));
        txtCierre.setText("CERRAR SESION");
        txtCierre.setContentAreaFilled(false);
        txtCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCierre.setFocusable(false);
        txtCierre.setOpaque(true);
        txtCierre.setPreferredSize(new java.awt.Dimension(100, 27));
        txtCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCierreActionPerformed(evt);
            }
        });
        pnlMenu.add(txtCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 177, -1));

        btnQA1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnQA1.setForeground(new java.awt.Color(44, 62, 80));
        btnQA1.setText("Q&A");
        btnQA1.setContentAreaFilled(false);
        btnQA1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnQA1.setFocusable(false);
        btnQA1.setPreferredSize(new java.awt.Dimension(100, 27));
        btnQA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQA1ActionPerformed(evt);
            }
        });
        pnlMenu.add(btnQA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 739, 235, -1));

        btnPadrePanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPadrePanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnPadrePanel.setForeground(new java.awt.Color(44, 62, 80));
        btnPadrePanel.setText("PADRE");
        btnPadrePanel.setToolTipText("b");
        btnPadrePanel.setBorder(null);
        btnPadrePanel.setContentAreaFilled(false);
        btnPadrePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPadrePanel.setFocusable(false);
        btnPadrePanel.setOpaque(true);
        btnPadrePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadrePanelActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPadrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, 40));

        btnAlumnoPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnoPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnAlumnoPanel.setForeground(new java.awt.Color(44, 62, 80));
        btnAlumnoPanel.setText("ALUMNO");
        btnAlumnoPanel.setToolTipText("b");
        btnAlumnoPanel.setBorder(null);
        btnAlumnoPanel.setContentAreaFilled(false);
        btnAlumnoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlumnoPanel.setFocusable(false);
        btnAlumnoPanel.setOpaque(true);
        btnAlumnoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoPanelActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAlumnoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 190, 40));

        btnProfesorPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnProfesorPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnProfesorPanel.setForeground(new java.awt.Color(44, 62, 80));
        btnProfesorPanel.setText("PROFESORES");
        btnProfesorPanel.setToolTipText("b");
        btnProfesorPanel.setBorder(null);
        btnProfesorPanel.setContentAreaFilled(false);
        btnProfesorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProfesorPanel.setFocusable(false);
        btnProfesorPanel.setOpaque(true);
        btnProfesorPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorPanelActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProfesorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 40));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 660));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusable(false);
        btnExit.setOpaque(true);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Exit (2).png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(255, 255, 255));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Maximize.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setFocusable(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Maximize (2).png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });
        btnMaximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizeActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setFocusable(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize (2).png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(729, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMaximize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 880, 30));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new java.awt.CardLayout());

        profesor.setBackground(new java.awt.Color(255, 255, 255));
        profesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarP.setBackground(new java.awt.Color(51, 0, 153));
        btnActualizarP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnActualizarP.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarP.setText("Actualizar");
        btnActualizarP.setToolTipText("b");
        btnActualizarP.setBorder(null);
        btnActualizarP.setContentAreaFilled(false);
        btnActualizarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizarP.setFocusable(false);
        btnActualizarP.setOpaque(true);
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });
        profesor.add(btnActualizarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 140, 40));

        tableProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre ", "Username", "Password", "Dirección", "Teléfono", "Email", "Género", "Fecha de Nacimiento", "Grado"
            }
        ));
        jScrollPane2.setViewportView(tableProfesor);

        profesor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 880, 330));

        btnEliminarP.setBackground(new java.awt.Color(51, 0, 153));
        btnEliminarP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnEliminarP.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarP.setText("Eliminar");
        btnEliminarP.setToolTipText("b");
        btnEliminarP.setBorder(null);
        btnEliminarP.setContentAreaFilled(false);
        btnEliminarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarP.setFocusable(false);
        btnEliminarP.setOpaque(true);
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });
        profesor.add(btnEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 130, 40));

        btnRegistrarP.setBackground(new java.awt.Color(51, 0, 153));
        btnRegistrarP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnRegistrarP.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarP.setText("Registrar");
        btnRegistrarP.setToolTipText("b");
        btnRegistrarP.setBorder(null);
        btnRegistrarP.setContentAreaFilled(false);
        btnRegistrarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarP.setFocusable(false);
        btnRegistrarP.setOpaque(true);
        btnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPActionPerformed(evt);
            }
        });
        profesor.add(btnRegistrarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 40));

        btnBuscarP.setBackground(new java.awt.Color(51, 0, 153));
        btnBuscarP.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnBuscarP.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarP.setText("Buscar");
        btnBuscarP.setToolTipText("b");
        btnBuscarP.setBorder(null);
        btnBuscarP.setContentAreaFilled(false);
        btnBuscarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarP.setFocusable(false);
        btnBuscarP.setOpaque(true);
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });
        profesor.add(btnBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 130, 40));

        pnlBody.add(profesor, "card2");

        alumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarA.setBackground(new java.awt.Color(51, 0, 153));
        btnBuscarA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnBuscarA.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarA.setText("Buscar");
        btnBuscarA.setToolTipText("b");
        btnBuscarA.setBorder(null);
        btnBuscarA.setContentAreaFilled(false);
        btnBuscarA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarA.setFocusable(false);
        btnBuscarA.setOpaque(true);
        btnBuscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAActionPerformed(evt);
            }
        });
        alumno.add(btnBuscarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 140, 40));

        btnRegistrarA.setBackground(new java.awt.Color(51, 0, 153));
        btnRegistrarA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnRegistrarA.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarA.setText("Registrar");
        btnRegistrarA.setToolTipText("b");
        btnRegistrarA.setBorder(null);
        btnRegistrarA.setContentAreaFilled(false);
        btnRegistrarA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarA.setFocusable(false);
        btnRegistrarA.setOpaque(true);
        btnRegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAActionPerformed(evt);
            }
        });
        alumno.add(btnRegistrarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, 40));

        btnEliminarA.setBackground(new java.awt.Color(51, 0, 153));
        btnEliminarA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnEliminarA.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarA.setText("Eliminar");
        btnEliminarA.setToolTipText("b");
        btnEliminarA.setBorder(null);
        btnEliminarA.setContentAreaFilled(false);
        btnEliminarA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarA.setFocusable(false);
        btnEliminarA.setOpaque(true);
        btnEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAActionPerformed(evt);
            }
        });
        alumno.add(btnEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 140, 40));

        btnModificarA.setBackground(new java.awt.Color(51, 0, 153));
        btnModificarA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnModificarA.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarA.setText("Modificar");
        btnModificarA.setToolTipText("b");
        btnModificarA.setBorder(null);
        btnModificarA.setContentAreaFilled(false);
        btnModificarA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarA.setFocusable(false);
        btnModificarA.setOpaque(true);
        btnModificarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAActionPerformed(evt);
            }
        });
        alumno.add(btnModificarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        alumno.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 770, 440));

        pnlBody.add(alumno, "card3");

        padre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarPadre.setBackground(new java.awt.Color(51, 0, 153));
        btnEliminarPadre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnEliminarPadre.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPadre.setText("Eliminar");
        btnEliminarPadre.setToolTipText("b");
        btnEliminarPadre.setBorder(null);
        btnEliminarPadre.setContentAreaFilled(false);
        btnEliminarPadre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarPadre.setFocusable(false);
        btnEliminarPadre.setOpaque(true);
        btnEliminarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPadreActionPerformed(evt);
            }
        });
        padre.add(btnEliminarPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 40));

        btnBuscarPadre.setBackground(new java.awt.Color(51, 0, 153));
        btnBuscarPadre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnBuscarPadre.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPadre.setText("Buscar");
        btnBuscarPadre.setToolTipText("b");
        btnBuscarPadre.setBorder(null);
        btnBuscarPadre.setContentAreaFilled(false);
        btnBuscarPadre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarPadre.setFocusable(false);
        btnBuscarPadre.setOpaque(true);
        btnBuscarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPadreActionPerformed(evt);
            }
        });
        padre.add(btnBuscarPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 140, 40));

        btnModificarPadre.setBackground(new java.awt.Color(51, 0, 153));
        btnModificarPadre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnModificarPadre.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPadre.setText("Modificar");
        btnModificarPadre.setToolTipText("b");
        btnModificarPadre.setBorder(null);
        btnModificarPadre.setContentAreaFilled(false);
        btnModificarPadre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarPadre.setFocusable(false);
        btnModificarPadre.setOpaque(true);
        btnModificarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPadreActionPerformed(evt);
            }
        });
        padre.add(btnModificarPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 40));

        btnRegistrarPadre.setBackground(new java.awt.Color(51, 0, 153));
        btnRegistrarPadre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnRegistrarPadre.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPadre.setText("Registrar");
        btnRegistrarPadre.setToolTipText("b");
        btnRegistrarPadre.setBorder(null);
        btnRegistrarPadre.setContentAreaFilled(false);
        btnRegistrarPadre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarPadre.setFocusable(false);
        btnRegistrarPadre.setOpaque(true);
        btnRegistrarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPadreActionPerformed(evt);
            }
        });
        padre.add(btnRegistrarPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        padre.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 870, 470));

        pnlBody.add(padre, "card4");

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 880, 630));

        setSize(new java.awt.Dimension(1120, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232,17,35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnMaximizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizeActionPerformed
        if(maximized){
            //handle fullscreen - taskbar
            DashboardAdmin.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            DashboardAdmin.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }//GEN-LAST:event_btnMaximizeActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        if(maximized){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void btnPadrePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadrePanelActionPerformed
        lblTimeline.setBackground(new Color(0,204,106));

        lblQA.setBackground(new Color(255,255,255));
        lblNews.setBackground(new Color(255,255,255));
        lblTrending.setBackground(new Color(255,255,255));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
          pnlBody.add(padre);
        pnlBody.repaint();
        pnlBody.revalidate();
      
    }//GEN-LAST:event_btnPadrePanelActionPerformed

    private void btnQA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQA1ActionPerformed

    private void txtCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCierreActionPerformed
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtCierreActionPerformed

    private void btnTrendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrendingActionPerformed
        lblTrending.setBackground(new Color(0,204,106));

        lblTimeline.setBackground(new Color(255,255,255));
        lblNews.setBackground(new Color(255,255,255));
        lblQA.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTrendingActionPerformed

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        lblTimeline.setBackground(new Color(0,204,106));

        lblQA.setBackground(new Color(255,255,255));
        lblNews.setBackground(new Color(255,255,255));
        lblTrending.setBackground(new Color(255,255,255));

        
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void btnAlumnoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoPanelActionPerformed
        lblTimeline.setBackground(new Color(0,204,106));

        lblQA.setBackground(new Color(255,255,255));
        lblNews.setBackground(new Color(255,255,255));
        lblTrending.setBackground(new Color(255,255,255));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(alumno);
        pnlBody.repaint();
        pnlBody.revalidate();
        
    }//GEN-LAST:event_btnAlumnoPanelActionPerformed

    private void btnProfesorPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorPanelActionPerformed
       lblTimeline.setBackground(new Color(0,204,106));

        lblQA.setBackground(new Color(255,255,255));
        lblNews.setBackground(new Color(255,255,255));
        lblTrending.setBackground(new Color(255,255,255));

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(profesor);
        pnlBody.repaint();
        pnlBody.revalidate();
        
        
        
    }//GEN-LAST:event_btnProfesorPanelActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPActionPerformed
       RegistroProfesor rp = new RegistroProfesor();
       rp.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnBuscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAActionPerformed

    private void btnRegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAActionPerformed
        registrarAlumno();
    }//GEN-LAST:event_btnRegistrarAActionPerformed

    private void btnEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAActionPerformed

    private void btnModificarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarAActionPerformed

    private void btnEliminarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPadreActionPerformed

    private void btnBuscarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPadreActionPerformed

    private void btnModificarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPadreActionPerformed

    private void btnRegistrarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPadreActionPerformed
        RegistroPadre p = new RegistroPadre();
        p.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPadreActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alumno;
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnAlumnoPanel;
    private javax.swing.JButton btnBuscarA;
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnBuscarPadre;
    private javax.swing.JButton btnEliminarA;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnEliminarPadre;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnModificarA;
    private javax.swing.JButton btnModificarPadre;
    private javax.swing.JButton btnPadrePanel;
    private javax.swing.JButton btnProfesorPanel;
    private javax.swing.JButton btnQA1;
    private javax.swing.JButton btnRegistrarA;
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JButton btnRegistrarPadre;
    private javax.swing.JButton btnTrending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblNews;
    private javax.swing.JLabel lblQA;
    private javax.swing.JLabel lblTimeline;
    private javax.swing.JLabel lblTrending;
    public javax.swing.JLabel lnlNombre;
    private javax.swing.JPanel padre;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel profesor;
    private javax.swing.JTable tableProfesor;
    private javax.swing.JButton txtCierre;
    // End of variables declaration//GEN-END:variables
    public void CargarProfesor(){
            try{
       
       tableProfesor.setModel(modelo);
       PreparedStatement ps = null;
       ResultSet rs = null;
       conexionBD conn = new conexionBD();
       Connection conexion = conn.getConection(); 
        
       String sql = "select prof_id, prof_nombre, prof_username, prof_password,prof_direccion,prof_telefono,prof_email,prof_genero,prof_fechaNacimiento,grado_id from tb_profesor";
       ps = conexion.prepareStatement(sql);
       rs = ps.executeQuery();
       ResultSetMetaData rsmd = rs.getMetaData();
       int cantidadColumna = rsmd.getColumnCount();
        modelo.addColumn("prof_id");
        modelo.addColumn("prof_nombre");
        modelo.addColumn("prof_username");
        modelo.addColumn("prof_password");
        modelo.addColumn("prof_direccion");
        modelo.addColumn("prof_telefono");
        modelo.addColumn("prof_email");
        modelo.addColumn("prof_genero");
        modelo.addColumn("prof_fechaNacimiento");
        modelo.addColumn("grado_id");
        
                while(rs.next()) {
                  Object[] filas = new Object[cantidadColumna];
                    for (int i = 0; i < cantidadColumna; i++) {
                        filas[i] = rs.getObject(i + 1);
                    }
                    modelo.addRow(filas);
                }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
    }

    private void registrarAlumno() {
      RegistroAlumno r = new RegistroAlumno();
      r.setVisible(true);
      
    }
}



