/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Calificacion;
import controlador.Cursos;
import controlador.Alumno;
import controlador.Profesor;
import controlador.Tarea;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Metodos_Admin;
import modelo.Metodos_sql;

/**
 *
 * @author Rahmans
 */
public class DashboardProfesor extends javax.swing.JFrame {

    static boolean maximized = true;
    int xMouse;
    int yMouse;
   
    Metodos_sql metodos = new Metodos_sql();
     
     Metodos_Admin metodosAdmin = new Metodos_Admin();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo1 = new DefaultTableModel(); 
       
   
    
    

    public DashboardProfesor() {
        initComponents();
        setLocationRelativeTo(null);
         Metodos_sql metodos = new Metodos_sql();
           DefaultComboBoxModel modelo_alumno = new DefaultComboBoxModel(metodosAdmin.llenarAlumno());
           DefaultComboBoxModel modelo_curso = new DefaultComboBoxModel(metodos.llenarCursos());
            cbxAlumno.setModel(modelo_alumno);
            cbxCursoNotas.setModel(modelo_curso);
            
             cbxAlumnoT.setModel(modelo_alumno);
            cbxCursoNotasT.setModel(modelo_curso);
            
            cbxAlumnoB.setModel(modelo_alumno);
            cbxCursoB.setModel(modelo_curso);
            
            
            modelo = (DefaultTableModel) tableCalificaciones.getModel();
            modelo1 = (DefaultTableModel) tableNotas.getModel();
    
        
        
        
    }
   
        
   

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lnlNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBandeja = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblQA = new javax.swing.JLabel();
        txtCierre = new javax.swing.JButton();
        lnlCodigo = new javax.swing.JLabel();
        btnRegistrar1 = new javax.swing.JButton();
        lblTrending1 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        panelBandeja = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        MENU_BANDEJA = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaB = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTemaB = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        cbxCursoB = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cbxAlumnoB = new javax.swing.JComboBox<>();
        registrarAlumno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxCursoNotas = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxAlumno = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCalificaciones = new javax.swing.JTable();
        registrarTareas = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cbxCursoNotasT = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbxAlumnoT = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtNombreT = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescT = new javax.swing.JTextArea();
        btnAgregarT = new javax.swing.JButton();
        btnLimpiarT = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableNotas = new javax.swing.JTable();
        bandeja = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cbxCursoNotasT1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cbxAlumnoT1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txtNombreT1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescT1 = new javax.swing.JTextArea();
        btnEnviarM = new javax.swing.JButton();
        btnLimpiarT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cube UI");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusable(false);
        btnExit.setOpaque(true);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Exit (2).png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(255, 255, 255));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Maximize.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setFocusable(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Maximize (2).png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });
        btnMaximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizeActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setFocusable(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Minimize (2).png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMaximize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/User.png"))); // NOI18N
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        lnlNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lnlNombre.setForeground(new java.awt.Color(44, 62, 80));
        pnlMenu.add(lnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 5, 226, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 140, 141));
        jLabel3.setText("Perfil");
        pnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 52, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 152, 219));
        jLabel5.setText("Learn More");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 42, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 140, 141));
        jLabel4.setText("Padre");
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 66, -1, -1));

        btnBandeja.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnBandeja.setForeground(new java.awt.Color(44, 62, 80));
        btnBandeja.setText("BANDEJA");
        btnBandeja.setContentAreaFilled(false);
        btnBandeja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBandeja.setFocusable(false);
        btnBandeja.setPreferredSize(new java.awt.Dimension(100, 27));
        btnBandeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBandejaMouseClicked(evt);
            }
        });
        btnBandeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBandejaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBandeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 105, -1));

        btnRegistrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(44, 62, 80));
        btnRegistrar.setText("REGISTRAR NOTAS");
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.setFocusable(false);
        btnRegistrar.setPreferredSize(new java.awt.Dimension(100, 27));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 196, -1));

        lblQA.setBackground(new java.awt.Color(255, 255, 255));
        lblQA.setOpaque(true);
        lblQA.setPreferredSize(new java.awt.Dimension(100, 0));
        pnlMenu.add(lblQA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 249, 110, 8));

        txtCierre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        txtCierre.setForeground(new java.awt.Color(44, 62, 80));
        txtCierre.setText("CERRAR SESION");
        txtCierre.setContentAreaFilled(false);
        txtCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCierre.setFocusable(false);
        txtCierre.setPreferredSize(new java.awt.Dimension(100, 27));
        txtCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCierreActionPerformed(evt);
            }
        });
        pnlMenu.add(txtCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 177, -1));

        lnlCodigo.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        lnlCodigo.setForeground(new java.awt.Color(44, 62, 80));
        pnlMenu.add(lnlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 104, 10, 24));

        btnRegistrar1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnRegistrar1.setForeground(new java.awt.Color(44, 62, 80));
        btnRegistrar1.setText("REGISTRAR TAREAS");
        btnRegistrar1.setContentAreaFilled(false);
        btnRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar1.setFocusable(false);
        btnRegistrar1.setPreferredSize(new java.awt.Dimension(100, 27));
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        pnlMenu.add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 210, -1));

        lblTrending1.setBackground(new java.awt.Color(255, 255, 255));
        lblTrending1.setOpaque(true);
        lblTrending1.setPreferredSize(new java.awt.Dimension(100, 0));
        pnlMenu.add(lblTrending1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 165, 10));

        pnlBody.setLayout(new java.awt.CardLayout());

        panelBandeja.setBackground(new java.awt.Color(245, 245, 245));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MENU_BANDEJA.addTab("MENSAJES", jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        txtAreaB.setColumns(20);
        txtAreaB.setForeground(new java.awt.Color(51, 0, 153));
        txtAreaB.setRows(5);
        txtAreaB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 153), null));
        jScrollPane1.setViewportView(txtAreaB);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(127, 140, 141));
        jLabel17.setText("DESCRIPCION :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(127, 140, 141));
        jLabel16.setText("TEMA :");

        txtTemaB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));

        btnEnviar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(44, 62, 80));
        btnEnviar.setText("ENVIAR");
        btnEnviar.setContentAreaFilled(false);
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.setFocusable(false);
        btnEnviar.setPreferredSize(new java.awt.Dimension(100, 27));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(127, 140, 141));
        jLabel32.setText("Curso :");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(127, 140, 141));
        jLabel33.setText("Alumno :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtTemaB, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCursoB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAlumnoB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTemaB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCursoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(cbxAlumnoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        MENU_BANDEJA.addTab("REDACTAR", jPanel8);

        javax.swing.GroupLayout panelBandejaLayout = new javax.swing.GroupLayout(panelBandeja);
        panelBandeja.setLayout(panelBandejaLayout);
        panelBandejaLayout.setHorizontalGroup(
            panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MENU_BANDEJA, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelBandejaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBandejaLayout.setVerticalGroup(
            panelBandejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandejaLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MENU_BANDEJA, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBody.add(panelBandeja, "card4");

        registrarAlumno.setBackground(new java.awt.Color(245, 245, 245));
        registrarAlumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Registrar notas");
        registrarAlumno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        registrarAlumno.add(cbxCursoNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Curso:");
        registrarAlumno.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Observaciones:");
        registrarAlumno.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        registrarAlumno.add(cbxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 250, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Alumno:");
        registrarAlumno.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        registrarAlumno.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Nota:");
        registrarAlumno.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane2.setViewportView(txtObservacion);

        registrarAlumno.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 310, 110));

        btnAgregar.setText("Registrar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        registrarAlumno.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        registrarAlumno.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        tableCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alumno", "Curso", "Nota", "Observaciones"
            }
        ));
        jScrollPane3.setViewportView(tableCalificaciones);

        registrarAlumno.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 470, 90));

        pnlBody.add(registrarAlumno, "card4");

        registrarTareas.setBackground(new java.awt.Color(245, 245, 245));
        registrarTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setText("Registrar tareas");
        registrarTareas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        registrarTareas.add(cbxCursoNotasT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Curso:");
        registrarTareas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Descripción :");
        registrarTareas.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        registrarTareas.add(cbxAlumnoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 250, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Alumno:");
        registrarTareas.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        registrarTareas.add(txtNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 320, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Tema:");
        registrarTareas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        txtDescT.setColumns(20);
        txtDescT.setRows(5);
        jScrollPane4.setViewportView(txtDescT);

        registrarTareas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 310, 110));

        btnAgregarT.setText("Registrar");
        btnAgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTActionPerformed(evt);
            }
        });
        registrarTareas.add(btnAgregarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        btnLimpiarT.setText("Limpiar");
        btnLimpiarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTActionPerformed(evt);
            }
        });
        registrarTareas.add(btnLimpiarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        tableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Alumno", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableNotas);

        registrarTareas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1060, 180));

        pnlBody.add(registrarTareas, "card4");

        bandeja.setBackground(new java.awt.Color(245, 245, 245));
        bandeja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setText("Enviar mensajes");
        bandeja.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        bandeja.add(cbxCursoNotasT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Curso:");
        bandeja.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Descripción :");
        bandeja.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        bandeja.add(cbxAlumnoT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 250, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Alumno:");
        bandeja.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        bandeja.add(txtNombreT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 320, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Tema:");
        bandeja.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        txtDescT1.setColumns(20);
        txtDescT1.setRows(5);
        jScrollPane6.setViewportView(txtDescT1);

        bandeja.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 510, 170));

        btnEnviarM.setText("Enviar");
        btnEnviarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMActionPerformed(evt);
            }
        });
        bandeja.add(btnEnviarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        btnLimpiarT1.setText("Limpiar");
        btnLimpiarT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarT1ActionPerformed(evt);
            }
        });
        bandeja.add(btnLimpiarT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        pnlBody.add(bandeja, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1120, 775));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232,17,35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnMaximizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizeActionPerformed
        if(maximized){
            //handle fullscreen - taskbar
            DashboardProfesor.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            DashboardProfesor.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }//GEN-LAST:event_btnMaximizeActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        if(maximized){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void btnBandejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBandejaActionPerformed
        
        lblQA.setBackground(new Color(255,255,255));
        
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(panelBandeja);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnBandejaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        lblQA.setBackground(new Color(255,255,255));
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(registrarAlumno);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCierreActionPerformed
      Login loginWindow = new Login();
      loginWindow.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_txtCierreActionPerformed

    private void btnBandejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBandejaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBandejaMouseClicked

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        try {
          String idProfesor =  metodos.buscarIdProfesor(lnlCodigo.getText());
           
         
           metodos.guardarMensaje(txtTemaB.getText(), txtAreaB.getText(), ((Alumno) cbxAlumnoB.getSelectedItem()).getIdAlumno(), ((Cursos)cbxCursoB.getSelectedItem()).getCodigo(),idProfesor);
           
           if (txtTemaB.getText().equals("") || txtAreaB.getText().equals("") || (((Alumno) cbxAlumnoB.getSelectedItem()).getIdAlumno()).equals("")) {
               JOptionPane.showMessageDialog(null,"Ingrese todos los campos");
            } else {
                JOptionPane.showMessageDialog(null,"Mensaje enviado");
            }
        } 
        catch (Exception e) {
            
            System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            /*Calificacion c = new Calificacion(((Alumno)cbxAlumno.getSelectedItem()).getIdAlumno(),((Cursos)cbxCurso.getSelectedItem()).getCodigo(), Integer.parseInt(txtNota.getText()),txtObservacion.getText());
      */
            Calificacion c = new Calificacion(((Alumno)cbxAlumno.getSelectedItem()).getNombreAlumno(),
                    ((Cursos)cbxCursoNotas.getSelectedItem()).getNombre(),
                    Integer.parseInt(txtNota.getText()),
                    txtObservacion.getText());
            
       metodos.adicionar(c);
        JOptionPane.showMessageDialog(null, "Registrado");
       //limpiar la tabla
        int filas = tableCalificaciones.getRowCount();
        for(int i=0; i<filas; i++)
                modelo.removeRow(0);
        
        //agregar la lista a la tabla
        //SI EL TAMAÑO DE LA LISTA DE PRODUCTO ES MAYOR A 0 
        if(metodos.totalCal()>0)
            // SE RECORRERA SIEMPRE Y CUANDO LA CONDICION SEA VERDADERA
            for(int i=0; i<metodos.totalCal(); i++){
                //SE AGREGA LOS PRODUCTOS EN CADA FILA
                modelo.addRow(new Object[]{
                    
                    metodos.obtener(i).getNombre(),
                    metodos.obtener(i).getCurso_id(),
                    metodos.obtener(i).getCal_nota(),
                    metodos.obtener(i).getCal_observacion()});
            } // SINO  HABRA UN MENSAJE DE NO LISTADO DE PRODUCTOS
        else JOptionPane.showMessageDialog(null, "No hay calificaciones para mostrar");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        metodos.guardarCalificacion(((Alumno)cbxAlumno.getSelectedItem()).getIdAlumno(), 
                 ((Cursos)cbxCursoNotas.getSelectedItem()).getCodigo(),
                Integer.parseInt(txtNota.getText()), 
                txtObservacion.getText());
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
      
        lblQA.setBackground(new Color(255,255,255));
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(registrarTareas);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnAgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTActionPerformed
        try {
            /*Calificacion c = new Calificacion(((Alumno)cbxAlumno.getSelectedItem()).getIdAlumno(),((Cursos)cbxCurso.getSelectedItem()).getCodigo(), Integer.parseInt(txtNota.getText()),txtObservacion.getText());
      */
            Tarea t= new Tarea(txtNombreT.getText(),txtDescT.getText(),((Alumno) cbxAlumnoT.getSelectedItem()).getIdAlumno(),((Cursos) cbxCursoNotasT.getSelectedItem()).getCodigo());
            
      metodos.adicionarTarea(t);
        JOptionPane.showMessageDialog(null, "Registrado");
       //limpiar la tabla
        int filas = tableNotas.getRowCount();
        for(int i=0; i<filas; i++)
                modelo1.removeRow(0);
        
        //agregar la lista a la tabla
        //SI EL TAMAÑO DE LA LISTA DE PRODUCTO ES MAYOR A 0 
        if(metodos.totalTarea()>0)
            // SE RECORRERA SIEMPRE Y CUANDO LA CONDICION SEA VERDADERA
            for(int i=0; i<metodos.totalTarea(); i++){
                //SE AGREGA LOS PRODUCTOS EN CADA FILA
                modelo1.addRow(new Object[]{
                    metodos.obtenerTarea(i).getNombre(),
                    metodos.obtenerTarea(i).getDesc(),  
                    metodos.obtenerTarea(i).getAlumno_carnet(),
                    metodos.obtenerTarea(i).getCurso_id()});
            } // SINO  HABRA UN MENSAJE DE NO LISTADO DE PRODUCTOS
        else JOptionPane.showMessageDialog(null, "No hay tareas para mostrar");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
       metodos.guardarTarea(txtNombreT.getText(),txtDescT.getText(),((Alumno) cbxAlumnoT.getSelectedItem()).getIdAlumno(),((Cursos) cbxCursoNotasT.getSelectedItem()).getCodigo());
    }//GEN-LAST:event_btnAgregarTActionPerformed

    private void btnLimpiarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarTActionPerformed

    private void btnEnviarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMActionPerformed
        
    }//GEN-LAST:event_btnEnviarMActionPerformed

    private void btnLimpiarT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarT1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardProfesor().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MENU_BANDEJA;
    private javax.swing.JPanel bandeja;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarT;
    private javax.swing.JButton btnBandeja;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviarM;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLimpiarT;
    private javax.swing.JButton btnLimpiarT1;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JComboBox<String> cbxAlumno;
    private javax.swing.JComboBox<String> cbxAlumnoB;
    private javax.swing.JComboBox<String> cbxAlumnoT;
    private javax.swing.JComboBox<String> cbxAlumnoT1;
    private javax.swing.JComboBox<String> cbxCursoB;
    private javax.swing.JComboBox<String> cbxCursoNotas;
    private javax.swing.JComboBox<String> cbxCursoNotasT;
    private javax.swing.JComboBox<String> cbxCursoNotasT1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblQA;
    private javax.swing.JLabel lblTrending1;
    public javax.swing.JLabel lnlCodigo;
    public javax.swing.JLabel lnlNombre;
    private javax.swing.JPanel panelBandeja;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel registrarAlumno;
    private javax.swing.JPanel registrarTareas;
    public javax.swing.JTable tableCalificaciones;
    public javax.swing.JTable tableNotas;
    private javax.swing.JTextArea txtAreaB;
    private javax.swing.JButton txtCierre;
    private javax.swing.JTextArea txtDescT;
    private javax.swing.JTextArea txtDescT1;
    private javax.swing.JTextField txtNombreT;
    private javax.swing.JTextField txtNombreT1;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtTemaB;
    // End of variables declaration//GEN-END:variables

}

